spring.application.name=SmartIndiaHackthon

server.port=8081

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/SIH
spring.datasource.username=root
spring.datasource.password=Muk#85etr

# JDBC Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

openweathermap.api.key=beee724417f4623efe66567e4e815c89


